// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJowtrzFrGUkYsMAkD-N01esTY24-PxyA',
    appId: '1:28902999546:web:9023f36964fd34a4765043',
    messagingSenderId: '28902999546',
    projectId: 'vipin-genai-bb',
    authDomain: 'vipin-genai-bb.firebaseapp.com',
    storageBucket: 'vipin-genai-bb.firebasestorage.app',
    measurementId: 'G-KDVP4D4D25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeT9UuieEku6tA0wVGpm9sq89_HS08nTI',
    appId: '1:28902999546:android:bcae2ff00884a972765043',
    messagingSenderId: '28902999546',
    projectId: 'vipin-genai-bb',
    storageBucket: 'vipin-genai-bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAge8MNDxtCwy2YcHgJaI0bFmYHUI52MkI',
    appId: '1:28902999546:ios:b703d86112fd9f2a765043',
    messagingSenderId: '28902999546',
    projectId: 'vipin-genai-bb',
    storageBucket: 'vipin-genai-bb.firebasestorage.app',
    iosBundleId: 'com.yorus.yorusMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAge8MNDxtCwy2YcHgJaI0bFmYHUI52MkI',
    appId: '1:28902999546:ios:b703d86112fd9f2a765043',
    messagingSenderId: '28902999546',
    projectId: 'vipin-genai-bb',
    storageBucket: 'vipin-genai-bb.firebasestorage.app',
    iosBundleId: 'com.yorus.yorusMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJowtrzFrGUkYsMAkD-N01esTY24-PxyA',
    appId: '1:28902999546:web:b359d760b412f4cb765043',
    messagingSenderId: '28902999546',
    projectId: 'vipin-genai-bb',
    authDomain: 'vipin-genai-bb.firebaseapp.com',
    storageBucket: 'vipin-genai-bb.firebasestorage.app',
    measurementId: 'G-XRFNFWB1NJ',
  );
}
