// lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart'; // For Isar path

import 'firebase_options.dart'; // Generated by flutterfire configure
import 'core/theme/yorus_theme.dart'; // We'll create this next
import 'data/local/models/media_item_model.dart'; // Isar model, create soon
import 'core/routing/app_router.dart'; // Import the new router

// Providers for core services
// (These will be moved to core/providers.dart later, but good to start here)

// Isar database provider
final isarProvider = FutureProvider<Isar>((ref) async {
  final dir = await getApplicationSupportDirectory();
  final isar = await Isar.open(
    [MediaItemSchema], // Add all your Isar schemas here
    directory: dir.path,
    name: 'yorus_db',
  );
  return isar;
});


void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Required for Firebase, Isar

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const ProviderScope(child: YorusApp()));
}

class YorusApp extends ConsumerWidget {
  const YorusApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp.router(
      title: 'Yorus',
      theme: YorusTheme.lightTheme, // Use our custom theme
      routerConfig: router, // Connect GoRouter to MaterialApp
      debugShowCheckedModeBanner: false,
    );
  }
}